FROM php:8.1.0-fpm

# Install system dependencies
RUN apt-get update && apt-get upgrade -y && dpkg --configure -a

RUN apt-get install -y -f \
    apt-utils \
    libjpeg62-turbo-dev  \
    libmcrypt-dev  \
    libpng-dev  \
    zlib1g-dev  \
    libxml2-dev  \
    libzip-dev  \
    libonig-dev  \
    graphviz  \
    git \
    curl \
    zip \
    unzip \
    nodejs \
    npm \
    wget 

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure gd \ 
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd sockets intl xml bcmath zip pcntl 

# Set working directory
WORKDIR /var/www

# COPY --chown=www-data:www-data . /var/www/

COPY --chown=www-data:www-data ./docker-entrypoint.sh /var/www/docker-entrypoint.sh

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN cp /var/www/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh && chmod +x /usr/local/bin/docker-entrypoint.sh