FROM mysql:8

RUN chown -R root:root /var/lib/mysql

RUN chgrp -R mysql /var/lib/mysql

WORKDIR /var/scripts

COPY ./.docker/.mysql/scripts /var/scripts/

COPY ./docker-entrypoint-database.sh /docker-entrypoint-initdb.d

EXPOSE 3306