version: '3.1'

services:
   # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./.docker/.nginx/:/etc/nginx/conf.d/
      - ./.docker/.nginx/logs:/var/log/nginx
    networks:
      - corridas-net

  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 120s docker-entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - corridas-net
    depends_on:
      - mysql
    tty: true
    restart: unless-stopped
  
  mysql:
    restart: always
    container_name: mysql
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/.mysql/db:/var/lib/mysql
    networks:
      - corridas-net
    tty: true

networks:
  corridas-net:
    driver: bridge